services:
  - type: web
    runtime: node
    name: st-edward-fund-dashboard
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: TENANT_ID
        sync: false
      - key: REDIRECT_URI
        value: https://lgl-dashboard.onrender.com/auth/callback
      - key: SESSION_SECRET
        generateValue: true
      - key: ALLOWED_DASHBOARD_USERS
        value: eharnisch@stedward.org,rcarroll@stedward.org,sblankenship@stedward.org,klewis@stedward.org,fatherbulso@stedward.org
