services:
  - type: web
    runtime: static
    name: st-edward-fund-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
